server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///hm49
    username: root
    password: haoxingqi497
  rabbitmq:
    host: 192.168.31.14 #rabbtimq的地址
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo